const TITLES = [
  "Ingrid Goes West",
  "The Northman",
  "Nosferatu",
  "Marriage Story",
  "Weapons",
  "The Last Unicorn",
  "The Secret of Kells",
  "A Monster Calls",
  "Mirrormask",
  "Ink",
  "A Whisker Away",
  "Mary and the Witch's Flower",
  "Prospect",
  "Fool's Paradise (Charlie Day)",
  "Before Sunrise",
  "From Dusk Till Dawn",
  "Tombstone",
  "The Ides of March",
  "The Quick and the Dead",
  "Justified",
  "Titanic",
  "Hit Man",
  "Waking Life",
  "Inception",
  "The Batman",
  "Hogfather",
  "Blade Runner",
  "Oldboy",
  "Face/Off",
  "Spawn",
  "Django Unchained",
  "Thoroughbreds",
  "Grindhouse",
  "The Imaginarium of Doctor Parnassus",
  "Mr. Nobody",
  "Stranger Things",
  "The Bourne Identity",
  "Kingsman",
  "Borat",
  "Harold & Kumar",
  "Office Space",
  "Stardust",
  "Layer Cake",
  "Baskets (Zach G and Louis CK)",
  "Dogma (Mallrats, etc.)",
  "Ace Ventura",
  "Drive",
  "Sin City",
  "The Gray Man",
  "The Cabin in the Woods",
  "Challengers",
  "Eternaut",
  "The Lost City (2022)",
  "The Neon Demon",
  "Color Out of Space",
  "Substance",
  "Poor Things",
  "Duster",
  "Sinner IMAX",
  "Booksmart",
  "Anora",
  "Adventures in Wonderland",
  "From Nand to Tetris",
  "Shiny Happy People",
  "The Looming Tower",
  "I'm Sorry",
  "Tulsa King",
];
