import {
  ShieldCheckIcon as ShieldCheck,
  UserMinusIcon as UserMinus,
  EyeSlashIcon as EyeSlash,
  StackIcon as Stack,
  type Icon,
} from "@phosphor-icons/react";
import {
  LANDING_TEAL,
  LANDING_PEACH,
  LANDING_PURPLE,
  LANDING_BLUE,
} from "./landingTheme";

export interface PrivacyPoint {
  icon: Icon;
  iconColor: string;
  title: string;
  description: string;
}

export interface PrivacyData {
  title: string;
  description: string;
  points: PrivacyPoint[];
}

export const landingPrivacy: PrivacyData = {
  title: "No Ads. No Subscriptions. No Data Selling. Ever.",
  description:
    "I'm not trying to monetize this. There's no ad network, no premium tier, no tracking pixel. You're not the product here - you're just someone using something I made.",
  points: [
    {
      icon: ShieldCheck,
      iconColor: LANDING_TEAL,
      title: "Free. Actually Free.",
      description:
        "No credit card. No trial period. No hidden upgrade. I built this for myself and I'm sharing it. That's the whole model.",
    },
    {
      icon: UserMinus,
      iconColor: LANDING_PEACH,
      title: "Your Data Isn't For Sale",
      description:
        "I don't sell it, analyze it for ads, or share it with anyone. Your lists, ratings, and activity exist only for you and whoever you've invited.",
    },
    {
      icon: EyeSlash,
      iconColor: LANDING_PURPLE,
      title: "No Tracking or Analytics",
      description:
        "No Google Analytics, no tracking pixels, no third-party scripts watching what you click. What you do in the app stays in the app.",
    },
    {
      icon: Stack,
      iconColor: LANDING_BLUE,
      title: "Invite-Only by Design",
      description:
        "No public sign-up means no strangers can show up. Every account comes from a code generated by someone already trusted.",
    },
  ],
};
